FROM grafana/grafana:master

LABEL MAINTAINER=DavyJ0nes
LABEL OWNER=DavyJ0nes

ENV GF_INSTALL_PLUGINS "fzakaria-simple-annotations-datasource,grafana-simple-json-datasource"
ENV GF_SECURITY_ADMIN_PASSWORD="hunter2"

EXPOSE 3000
